### ISSUE TITLE
生成的液态二维码上面有很多白色的直线，怎么解决？

### ISSUE THREAD

**Issue by ouyangpeng** [Y-bao/QRCodeYbao#3]
您好，根据您的算法，我测试了下demo

当二维码原始数据为类似下面的格式的时候，生成的液态二维码是有很多白色直线的，如下所示：

```
 String cev = "http://watch.okii.com/d/abcdefghijklmn";
```

![image](https://user-images.githubusercontent.com/5885735/50499156-4a4b8400-0a82-11e9-9ffc-43559ba51e96.png)

![image](https://user-images.githubusercontent.com/5885735/50499192-9dbdd200-0a82-11e9-9071-f6ad6ab20a5e.png)

``` String cev = "http://blog.csdn.net/d/abcdefghijklmn";```

![snipaste_2018-12-28_09-32-37](https://user-images.githubusercontent.com/5885735/50499293-94813500-0a83-11e9-9e0a-81b73f00805d.jpg)

``` String cev = "http://blog.csdn.net/download/abcdefghijklmn";```

![a2](https://user-images.githubusercontent.com/5885735/50499351-03f72480-0a84-11e9-9cbb-5317e3cd089d.jpg)

``` String cev = "String cev = "https://www.hao123.com/?tn=99682755_hao_pg";```

![image](https://user-images.githubusercontent.com/5885735/50499420-7a942200-0a84-11e9-8b5a-345c63989c19.png)

请问这个算法有没有办法可以去掉这些白线呢？

@Y-bao

**Comment by pierreown** [comment]
已解决
